name: CI
on:
  push:
    branches: ["main"]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest-4-cores
    steps:
      - name: Pull code
        uses: actions/checkout@v3

      - name: Docker
        run: |
          docker build -t todo-list-website .
          docker save -o todo-list-website.tar todo-list-website

      - name: Copy Docker image to ec2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.STAGE_SERVER_HOST }}
          username: ubuntu
          port: 22
          key: ${{ secrets.STAGE_SERVER_KEY_SSH }}
          source: "todo-list-website.tar,docker-compose.yml"
          target: "~/todo-list-website"

      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.STAGE_SERVER_HOST }}
          username: ubuntu
          port: 22
          key: ${{ secrets.STAGE_SERVER_KEY_SSH }}
          script: |
            cd ~/todo-list-website
            sudo snap install docker
            sudo docker load --input todo-list-website.tar
            sudo docker-compose up -d --force-recreate
