name: Test before merge to staging with cache node module

on:
  pull_request:
    branches: ["main"]

jobs:
  test:
    name: "CI: Test with ESLint and Cypress headless (comming soon)"
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3

      - uses: actions/cache@v3
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install packages
        run: yarn install

      - name: Run Typescript Checks
        run: yarn build
