name: Test before merge to staging

on:
  pull_request:
    branches: ["main"]

jobs:
  test:
    name: "CI: Test with ESLint and Cypress headless (comming soon)"
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }} for run testing (CI)
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: ESLint Check
        run: npm install -g yarn && yarn && yarn lint
